# 使用 Node.js 22 的轻量级 Alpine 镜像
FROM node:22-alpine

# 设置工作目录
WORKDIR /app

# 复制项目所有文件
COPY . .

# 安装项目所有依赖
RUN npm install

# 执行后端的打包命令
RUN npm run server:build

# 暴露后端运行的 3000 端口
EXPOSE 3000

# 启动后端服务
CMD ["npm", "run", "server:start"]